# Generated by Django 4.2.4 on 2023-09-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_worker_more_alter_worker_preum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.FileField(default='logos/logo1.png', upload_to='ramlar/', verbose_name='rasmingizni joylang'),
        ),
    ]
