# Generated by Django 4.2.4 on 2023-09-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_worker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.FileField(upload_to='ramlar/', verbose_name='rasmingizni joylang'),
        ),
    ]
